sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8.3'
after_success:
  - npx semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
